# モデルの自動テスト用GitHub Actionsワークフロー
# mainブランチへのpushやpull request時に自動でテストを実行します
# day5/演習1/tests/test_model.py のテストが実行され、品質が担保されます

name: Model Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: ソースコードの取得
      uses: actions/checkout@v2
    
    - name: Pythonのセットアップ
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: 依存パッケージのインストール
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: モデルテストの実行
      run: |
        PYTHONPATH=$PYTHONPATH:. pytest day5/演習1/tests/ --cov=day5/演習1 --cov-report=xml
    
    # カバレッジレポートのアップロード（任意・必要な場合のみ）
    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v2
    #   with:
    #     file: ./coverage.xml
    #     fail_ci_if_error: true
